/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/[id]': RouteRecordInfo<'/components/[id]', '/components/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/components/forms/': RouteRecordInfo<'/components/forms/', '/components/forms', Record<never, never>, Record<never, never>>,
    '/components/forms/[id]': RouteRecordInfo<'/components/forms/[id]', '/components/forms/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/components/modals/': RouteRecordInfo<'/components/modals/', '/components/modals', Record<never, never>, Record<never, never>>,
    '/components/modals/[id]': RouteRecordInfo<'/components/modals/[id]', '/components/modals/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
